### ISSUE TITLE
Error alert when running "val_dataset.run_eval()"

### ISSUE THREAD

**Issue by LouisNUST** [tensorboy/centerpose#20]
Traceback (most recent call last):
File "/home/centerpose/tools/train.py", line 151, in
main(cfg, local_rank)
File "/home/centerpose/tools/train.py", line 120, in main
mAP = val_dataset.run_eval(preds, cfg.OUTPUT_DIR)
File "/home/centerpose/tools/../lib/datasets/coco_hp.py", line 100, in run_eval
coco_dets = self.coco.loadRes(self.convert_eval_format(results))
File "/home/centerpose/tools/../lib/datasets/coco_hp.py", line 64, in convert_eval_format
bbox = dets[:4]
IndexError: invalid index to scalar variable.

**Comment by tensorboy** [comment]
Hi, @LouisNUST are you running the most recent code?

**Comment by LouisNUST** [comment]
@tensorboy Thanks a lot, recent version works well.
